// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARfvVNmDH27oXjqBdEPqVpGW2zyIXTbkI',
    appId: '1:159984612460:web:28423cd2e6503ca7331449',
    messagingSenderId: '159984612460',
    projectId: 'house-management-app-ffb17',
    authDomain: 'house-management-app-ffb17.firebaseapp.com',
    storageBucket: 'house-management-app-ffb17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3O1G16zAP9PKIZqNnig76aQkHSUjnrIo',
    appId: '1:159984612460:android:c1d29f3d5c03b62a331449',
    messagingSenderId: '159984612460',
    projectId: 'house-management-app-ffb17',
    storageBucket: 'house-management-app-ffb17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkN10vCjaVjCIz2tGh4smUyw4oRSga1I8',
    appId: '1:159984612460:ios:d2d3069895eb8714331449',
    messagingSenderId: '159984612460',
    projectId: 'house-management-app-ffb17',
    storageBucket: 'house-management-app-ffb17.appspot.com',
    iosBundleId: 'com.example.houseManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkN10vCjaVjCIz2tGh4smUyw4oRSga1I8',
    appId: '1:159984612460:ios:d2d3069895eb8714331449',
    messagingSenderId: '159984612460',
    projectId: 'house-management-app-ffb17',
    storageBucket: 'house-management-app-ffb17.appspot.com',
    iosBundleId: 'com.example.houseManagementApp',
  );
}
